package main

import (
	"encoding/json"
	"fmt"
	"time"
	"github.com/google/uuid" // For generating WillID
	"github.com/hyperledger/fabric-contract-api-go/contractapi"
)

// ABstore Chaincode implementation (Reverted to original example name)
type ABstore struct { // 이름 변경: DigitalWillChaincode -> ABstore
	contractapi.Contract
}

// Will defines the structure for a digital will.
// It includes a docType field to help distinguish it from other asset types in rich queries.
type Will struct {
	ObjectType         string   `json:"docType"`          // Should be "will"
	WillID             string   `json:"willID"`           // Unique ID for the will, generated by the system
	TestatorID         string   `json:"testatorID"`       // ID of the person making the will (from client identity)
	Title              string   `json:"title"`            // User-defined title for the will
	ContentHash        string   `json:"contentHash"`      // Hash of the encrypted will content (actual content stored off-chain)
	OffChainStorageRef string   `json:"offChainStorageRef"` // Optional: Reference to where the encrypted content is stored (e.g., IPFS CID, URL)
	Beneficiaries      []string `json:"beneficiaries"`    // List of beneficiary identifiers (e.g., DIDs, names, or other unique IDs)
	CreationTimestamp  int64    `json:"creationTimestamp"`// Unix timestamp of will creation
	LastUpdatedTimestamp int64  `json:"lastUpdatedTimestamp"` // Unix timestamp of the last update to the will
	Status             string   `json:"status"`           // Status of the will, e.g., "ACTIVE", "REVOKED", "PENDING_VERIFICATION"
}

// InitLedger is called when the chaincode is instantiated or upgraded.
func (s *ABstore) InitLedger(ctx contractapi.TransactionContextInterface) error { // 리시버 변경
	fmt.Println("ABstore: InitLedger invoked") // 로그 메시지 변경
	// 이 예제에서는 유언장 기능에 특화된 초기화는 필요하지 않습니다.
	return nil
}

// RegisterWill creates a new digital will on the ledger.
func (s *ABstore) RegisterWill(ctx contractapi.TransactionContextInterface, title string, contentHash string, offChainStorageRef string, beneficiariesJSON string) (string, error) { // 리시버 변경
	fmt.Printf("ABstore.RegisterWill: Attempting to register will with Title='%s', ContentHash (first 10)='%s...', OffChainRef='%s'\n", // 로그 메시지 변경
		title, firstN(contentHash, 10), offChainStorageRef)

	if title == "" {
		return "", fmt.Errorf("title cannot be empty")
	}
	if contentHash == "" {
		return "", fmt.Errorf("contentHash cannot be empty; it's crucial for verifying off-chain content")
	}

	testatorID, err := getSubmitterID(ctx)
	if err != nil {
		return "", fmt.Errorf("failed to get submitter ID: %w", err)
	}

	beneficiaries := make([]string, 0)
	if beneficiariesJSON != "" {
		err = json.Unmarshal([]byte(beneficiariesJSON), &beneficiaries)
		if err != nil {
			return "", fmt.Errorf("failed to unmarshal beneficiaries JSON string '%s': %w", beneficiariesJSON, err)
		}
	}

	willID := uuid.New().String()
	timestamp := time.Now().Unix()

	will := Will{
		ObjectType:         "will",
		WillID:             willID,
		TestatorID:         testatorID,
		Title:              title,
		ContentHash:        contentHash,
		OffChainStorageRef: offChainStorageRef,
		Beneficiaries:      beneficiaries,
		CreationTimestamp:  timestamp,
		LastUpdatedTimestamp: timestamp,
		Status:             "ACTIVE",
	}

	willJSON, err := json.Marshal(will)
	if err != nil {
		return "", fmt.Errorf("failed to marshal will struct to JSON: %w", err)
	}

	err = ctx.GetStub().PutState(willID, willJSON)
	if err != nil {
		return "", fmt.Errorf("failed to put will %s to world state: %w", willID, err)
	}

	fmt.Printf("ABstore.RegisterWill: Successfully registered will ID '%s' for testator '%s'\n", willID, testatorID) // 로그 메시지 변경
	return willID, nil
}

// GetWillDetails retrieves a specific will by its ID from the ledger.
func (s *ABstore) GetWillDetails(ctx contractapi.TransactionContextInterface, willID string) (*Will, error) { // 리시버 변경
	fmt.Printf("ABstore.GetWillDetails: Attempting to retrieve will with ID '%s'\n", willID) // 로그 메시지 변경

	if willID == "" {
		return nil, fmt.Errorf("willID cannot be empty")
	}

	willJSON, err := ctx.GetStub().GetState(willID)
	if err != nil {
		return nil, fmt.Errorf("failed to read will '%s' from world state: %w", willID, err)
	}
	if willJSON == nil {
		return nil, fmt.Errorf("will '%s' does not exist", willID)
	}

	var will Will
	err = json.Unmarshal(willJSON, &will)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal JSON for will '%s': %w", willID, err)
	}

	callerID, err := getSubmitterID(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get submitter ID for access control check: %w", err)
	}

	if will.TestatorID != callerID {
		return nil, fmt.Errorf("access denied: caller '%s' is not the testator of will '%s'. Only the testator can view details.", firstN(callerID, 20), willID)
	}

	fmt.Printf("ABstore.GetWillDetails: Successfully retrieved will ID '%s' for testator '%s'\n", willID, will.TestatorID) // 로그 메시지 변경
	return &will, nil
}

// GetMyWills retrieves all wills created by the calling user (testator).
func (s *ABstore) GetMyWills(ctx contractapi.TransactionContextInterface) ([]*Will, error) { // 리시버 변경
	fmt.Println("ABstore.GetMyWills: Retrieving all wills for the current submitter") // 로그 메시지 변경

	testatorID, err := getSubmitterID(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get submitter ID: %w", err)
	}

	resultsIterator, err := ctx.GetStub().GetStateByRange("", "")
	if err != nil {
		return nil, fmt.Errorf("failed to get state by range: %w", err)
	}
	defer resultsIterator.Close()

	var myWills []*Will
	for resultsIterator.HasNext() {
		queryResponse, err := resultsIterator.Next()
		if err != nil {
			return nil, fmt.Errorf("failed to get next state from iterator: %w", err)
		}

		var will Will
		if errUnmarshal := json.Unmarshal(queryResponse.Value, &will); errUnmarshal != nil {
			// fmt.Printf("Skipping asset %s, not a valid Will object: %s\n", queryResponse.Key, errUnmarshal.Error())
			continue
		}

		if will.ObjectType == "will" && will.TestatorID == testatorID {
			myWills = append(myWills, &will)
		}
	}

	if len(myWills) == 0 {
		fmt.Printf("ABstore.GetMyWills: No wills found for testator '%s'\n", firstN(testatorID, 20)) // 로그 메시지 변경
	} else {
		fmt.Printf("ABstore.GetMyWills: Found %d wills for testator '%s'\n", len(myWills), firstN(testatorID,20)) // 로그 메시지 변경
	}
	return myWills, nil
}

// getSubmitterID retrieves the unique ID of the client submitting the transaction.
func getSubmitterID(ctx contractapi.TransactionContextInterface) (string, error) {
	clientID, err := ctx.GetClientIdentity().GetID()
	if err != nil {
		return "", fmt.Errorf("failed to get client ID from context: %w", err)
	}
	if clientID == "" {
		return "", fmt.Errorf("client ID is empty; cannot identify the submitter. Ensure client identity is correctly configured in the network and application")
	}
	return clientID, nil
}

// Helper function to get the first N characters of a string (for logging long strings)
func firstN(s string, n int) string {
    if len(s) > n {
        return s[:n]
    }
    return s
}

// main function starts the chaincode in the container environment.
func main() {
	chaincode, err := contractapi.NewChaincode(new(ABstore)) // 생성자 변경
	if err != nil {
		fmt.Printf("Error creating ABstore chaincode: %s\n", err.Error()) // 에러 메시지 변경
		return
	}

	if err := chaincode.Start(); err != nil {
		fmt.Printf("Error starting ABstore chaincode: %s\n", err.Error()) // 에러 메시지 변경
	}
}